export * from './component/Header/Header';
export * from './component/Footer/Footer';
export * from '../pages/Home/Home';
export * from '../pages/Contact/Contact';
export * from '../pages/Menu/Menu';
export * from '../pages/About/About';
export * from './component/Card/Card';
export * from './component/NotFound/NotFound';
export * from './component/MainCard/MainCard';
export * from './component/Cards/Cards'